name: maps_flutter
description: "Mapa interactivo con marcadores guardados en Supabase y ubicación actual."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^1.10.16

  # Mapa con OpenStreetMap
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Para obtener la ubicación actual (GPS)
  geolocator: ^12.0.0

  # Para rutas y polilíneas
  flutter_polyline_points: ^2.0.0

  # Utilidades
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true